### ISSUE TITLE
Performance issue when large jsons are diff

### ISSUE THREAD

**Issue by number-00** [RexSkz/json-diff-kit#11]
the react app crashes when i try to compare json file of size: 3.3mb

**Comment by number-00** [comment]
Also I am unable to scroll the page when the JSON object is big and there are lot of additions.
Do help to suggest any solutions.

**Comment by number-00** [comment]
@RexSkz can the diff results be displayed in image format so that are less html nodes on the page and there is no lag while scrolling?

**Comment by RexSkz** [comment]
The library now supports virtual scroll. It seems to work well with a JSON that is 4MB with 200 million result lines. The diff process takes about 3 seconds, and it won't be slow when scrolling.

Using images to replace DOMs may not be a good idea because the browser will spend more resources to generate/display them.
