### ISSUE TITLE
Sytax highligting with prism

### ISSUE THREAD

**Issue by TipicultBiomassa** [RexSkz/json-diff-kit#17]
How can i do sytax highligting? For example with prism. Is it possible with default viewer?

**Comment by RexSkz** [comment]
Good idea! *It's not supported now, but I'm going to implement it in `Viewer`.*

Prism is a good syntax-highlighting library (I use it in lots of projects), but it's too wasteful for highlighting JSON, and I need to take some extra steps to align the unchanged lines.

I'll add a new prop to `Viewer`:

```ts
interface ViewerProps {
  syntaxHighlightTheme?: string;
}
```

It will enable the syntax highlight feature and add a class `json-diff-viewer-theme-${syntaxHighlightTheme}` to the viewer for CSS to take effect.

I'll provide a theme "monokai" first (which is my favourite theme), other themes may be added in future (by me or by others).

**Comment by RexSkz** [comment]
Sorry for being late; I've finished the syntax highlight feature, but the usage is different from the beginning since there're inline diff and I need to handle the two segment array (inline diff result & syntax highlight result) in `<Viewer>` component.

The playground has been updated, just check the "syntax highlight" checkbox on the left to enable it:

![image](https://github.com/RexSkz/json-diff-kit/assets/27483702/e713bf27-4221-4734-8348-2a3c232914e2)

The usage in your code is simple:

1. Add `syntaxHighlight={{ theme: 'monokai' }}` to the `<Viewer>` component is enough (other `theme` values are ok, it will enable the syntax highlight feature and add a className `json-diff-viewer-theme-monokai` to the DOM).
2. Import the CSS which has the corresponding theme. For now I only support the monokai theme, which is at `'json-diff-kit/dist/viewer-monokai.css'`, you can write your own theme according to this file.
