### ISSUE TITLE
Comparing array from the end in some cases

### ISSUE THREAD

**Issue by TanjaZzz** [RexSkz/json-diff-kit#21]
Hi!
Could you fix this bug, please?

When we compare `k` here, we compare 1 to 1 from the beginning of the array.
And when we compare `d` here, we compare 1 to 1 from the end of the array, that looks like a bug and` {a: 1}, {b: 2}` should be shown as equal for `before` and `after.`

```
const before = {
  d: [{a: 1}, {b: 2}, {c: 4}, {d: 4}],
  k: [1, 2, 5],
};
const after = {
  d: [{a: 1}, {b: 2}],
  k: [1, 2],
};
```
<img width="588" alt="Screenshot 2023-10-03 at 19 17 07" src="https://github.com/RexSkz/json-diff-kit/assets/51056474/aa893341-19d3-4605-aa4b-268711aba994">

**Comment by RexSkz** [comment]
You can set `recursiveEqual: true` at Differ options, which should generate a result in more common sense:

![image](https://github.com/RexSkz/json-diff-kit/assets/27483702/5a88a112-5783-48c5-a934-f59d839cc362)

P.S. During the test case I found a bug in the line number display (the last line at the left should be `21` instead of `14`), I'll fix it soon.

**Comment by TanjaZzz** [comment]
Unfortunately, it seems to not have any impact only adding `recursiveEqual: true` at Differ options

<img width="1149" alt="Screenshot 2023-10-04 at 11 03 41" src="https://github.com/RexSkz/json-diff-kit/assets/51056474/3b1cb64b-54ec-4ae6-b816-62b753350411">
