### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by YunesHou** [RexSkz/json-diff-kit#3]
Hi, thank you so much for creating the tool to compare json array. But when I built it, I faced an error like this:
<img width="906" alt="Screen Shot 2022-08-24 at 12 05 14 PM" src="https://user-images.githubusercontent.com/32113772/186480128-44f0d938-368f-477b-a6c0-c02b9936b497.png">
Is there any way that I can fix this issue? Thanks!

**Comment by RexSkz** [comment]
This may due to the `?.` operator. The `json-diff-kit` only provides ES6 version (not ES5), so if your bundler can't handle ES6 syntax, you should compile it using the compiler. If you use `babel-loader`, you can add an option `exclude`, which tells babel to compile the `json-diff-kit`:

```javascript
{
    loader: 'babel-loader',
    options: {
        presets: [...],
        exclude: /node_modules\/(?!json-diff-kit).+/,
    },
}
```

Hope this will help :)
